/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Network.Network;
import Business.Organization.NGOAdminOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ClothesRequirementRequest;
import Business.WorkQueue.Products;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akshitvarma
 */
public class RequestClothesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestClothesJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private EcoSystem business;
   

    public RequestClothesJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.business = business;
        valueLabel.setText(enterprise.getName());

        comboSummerProduct.setEnabled(false);
        comboWomenProducts.setEnabled(false);
        comboWinterProduct.setEnabled(false);
        comboRainyProducts.setEnabled(false);
        comboJacketProducts.setEnabled(false);
        comboFootWearProducts.setEnabled(false);
        
        quantSummer.setEnabled(false);
        quantWomen.setEnabled(false);
        quantWinter.setEnabled(false);
        quantFootWear.setEnabled(false);
        quantRainy.setEnabled(false);
        quantJackets.setEnabled(false);
        
        //btnReset.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        comboSummerProduct = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        checkSummerWear = new javax.swing.JCheckBox();
        checkWinterWear = new javax.swing.JCheckBox();
        checkRainyWear = new javax.swing.JCheckBox();
        checkWomenWear = new javax.swing.JCheckBox();
        checkJackets = new javax.swing.JCheckBox();
        checkFootWear = new javax.swing.JCheckBox();
        quantSummer = new javax.swing.JSpinner();
        comboWinterProduct = new javax.swing.JComboBox<>();
        comboRainyProducts = new javax.swing.JComboBox<>();
        comboWomenProducts = new javax.swing.JComboBox<>();
        comboJacketProducts = new javax.swing.JComboBox<>();
        comboFootWearProducts = new javax.swing.JComboBox<>();
        quantWinter = new javax.swing.JSpinner();
        quantRainy = new javax.swing.JSpinner();
        quantFootWear = new javax.swing.JSpinner();
        quantJackets = new javax.swing.JSpinner();
        quantWomen = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        backJButton1 = new javax.swing.JButton();
        enterpriseLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 0, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        requestTestJButton.setText("Submit Request");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 406, 338, 44));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quantity:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 94, -1, -1));
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 359, 226, -1));

        btnReset.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        btnReset.setText("Reset Options");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 338, 39));

        valueLabel.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(255, 255, 255));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 260, -1));

        enterpriseLabel.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setText("Summarize Items:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 240, 30));

        comboSummerProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shirts", "Shorts", "Dresses" }));
        add(comboSummerProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 127, 72, -1));

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Clothes Type:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 94, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Product:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 94, -1, -1));

        checkSummerWear.setBackground(new java.awt.Color(153, 153, 153));
        checkSummerWear.setForeground(new java.awt.Color(255, 255, 255));
        checkSummerWear.setText("Summer Wear");
        checkSummerWear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSummerWearActionPerformed(evt);
            }
        });
        add(checkSummerWear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 126, -1, -1));

        checkWinterWear.setBackground(new java.awt.Color(153, 153, 153));
        checkWinterWear.setForeground(new java.awt.Color(255, 255, 255));
        checkWinterWear.setText("Winter Wear");
        checkWinterWear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkWinterWearActionPerformed(evt);
            }
        });
        add(checkWinterWear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 157, -1, -1));

        checkRainyWear.setBackground(new java.awt.Color(153, 153, 153));
        checkRainyWear.setForeground(new java.awt.Color(255, 255, 255));
        checkRainyWear.setText("Rainy Wear");
        checkRainyWear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRainyWearActionPerformed(evt);
            }
        });
        add(checkRainyWear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 188, -1, -1));

        checkWomenWear.setBackground(new java.awt.Color(153, 153, 153));
        checkWomenWear.setForeground(new java.awt.Color(255, 255, 255));
        checkWomenWear.setText("Women Wear");
        checkWomenWear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkWomenWearActionPerformed(evt);
            }
        });
        add(checkWomenWear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 219, -1, -1));

        checkJackets.setBackground(new java.awt.Color(153, 153, 153));
        checkJackets.setForeground(new java.awt.Color(255, 255, 255));
        checkJackets.setText("Jackets");
        checkJackets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkJacketsActionPerformed(evt);
            }
        });
        add(checkJackets, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        checkFootWear.setBackground(new java.awt.Color(153, 153, 153));
        checkFootWear.setForeground(new java.awt.Color(255, 255, 255));
        checkFootWear.setText("FootWear");
        checkFootWear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFootWearActionPerformed(evt);
            }
        });
        add(checkFootWear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 281, -1, -1));

        quantSummer.setModel(new javax.swing.SpinnerNumberModel(0, 0, 500, 1));
        add(quantSummer, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 127, -1, -1));

        comboWinterProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coats", "Gloves", "Hats" }));
        add(comboWinterProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 158, 72, -1));

        comboRainyProducts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coats", "Boots", "N/A" }));
        add(comboRainyProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 189, 72, -1));

        comboWomenProducts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NA", "NA", "NA" }));
        add(comboWomenProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 220, 72, -1));

        comboJacketProducts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Field Jackets", "Denim", "Bomber" }));
        add(comboJacketProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 251, -1, -1));

        comboFootWearProducts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sandals", "Flip Flops", "Shoes" }));
        add(comboFootWearProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 282, 72, -1));

        quantWinter.setModel(new javax.swing.SpinnerNumberModel(0, 0, 500, 1));
        add(quantWinter, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 158, -1, -1));

        quantRainy.setModel(new javax.swing.SpinnerNumberModel(0, 0, 500, 1));
        add(quantRainy, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 189, -1, -1));

        quantFootWear.setModel(new javax.swing.SpinnerNumberModel(0, 0, 500, 1));
        add(quantFootWear, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 282, -1, -1));

        quantJackets.setModel(new javax.swing.SpinnerNumberModel(0, 0, 500, 1));
        add(quantJackets, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 251, -1, -1));

        quantWomen.setModel(new javax.swing.SpinnerNumberModel(0, 0, 500, 1));
        add(quantWomen, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Comment Message:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 362, -1, -1));

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clothes Type", "Product", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProducts);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        backJButton1.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        backJButton1.setText("Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 461, 338, 39));

        enterpriseLabel1.setFont(new java.awt.Font("Academy Engraved LET", 1, 24)); // NOI18N
        enterpriseLabel1.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel1.setText("Enterprise :");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 280, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        //******************* Validation *********************
        
         if(!(checkSummerWear.isSelected()) && !(checkWinterWear.isSelected()) && !(checkRainyWear.isSelected()) && !(checkWomenWear.isSelected()) && !(checkJackets.isSelected())){
            
            JOptionPane.showMessageDialog(null, "Please Select Products!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
         String mess = messageJTextField.getText();
         if (mess.equalsIgnoreCase("")) {

            JOptionPane.showMessageDialog(null, "Please add comments", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
         
        //**************************************

         int check=0;
       
         String message = messageJTextField.getText();
       
        ArrayList<Products> productList = new ArrayList<>();
        
        if (checkSummerWear.isSelected()) {
            
            if(quantSummer.getValue().equals(check)){
                
                JOptionPane.showMessageDialog(null, "Please Add Quantity!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
           
            Products p = new Products();
            p.setProductName(String.valueOf(comboSummerProduct.getSelectedItem()));
            p.setProductType("Summer Wear");
            p.setQuantity((Integer) quantSummer.getValue());
            productList.add(p);
            populateData(productList);
        }
        if (checkFootWear.isSelected()) {
            
            if(quantFootWear.getValue().equals(check)){
                
                JOptionPane.showMessageDialog(null, "Please Add Quantity!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Products p = new Products();
            p.setProductName(String.valueOf(comboFootWearProducts.getSelectedItem()));
            p.setProductType("WinterWear");
            p.setQuantity((Integer) quantFootWear.getValue());
             productList.add(p);
             populateData(productList);
        }
        if (checkJackets.isSelected()) {
            
            if(quantJackets.getValue().equals(check)){
                
                JOptionPane.showMessageDialog(null, "Please Add Quantity!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Products p = new Products();
            p.setProductName(String.valueOf(comboJacketProducts.getSelectedItem()));
            p.setProductType("Rainy Wear");
            p.setQuantity((Integer) quantJackets.getValue());
             productList.add(p);
             populateData(productList);
        }
        if (checkWomenWear.isSelected()) {
            
            if(quantWomen.getValue().equals(check)){
                
                JOptionPane.showMessageDialog(null, "Please Add Quantity!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Products p = new Products();
            p.setProductName(String.valueOf(comboWomenProducts.getSelectedItem()));
            p.setProductType("Women Wear");
            p.setQuantity((Integer) quantWomen.getValue());
            productList.add(p);
            populateData(productList);
        }
        if (checkRainyWear.isSelected()) {
            
            if(quantRainy.getValue().equals(check)){
                
                JOptionPane.showMessageDialog(null, "Please Add Quantity!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Products p = new Products();
            p.setProductName(String.valueOf(comboRainyProducts.getSelectedItem()));
            p.setProductType("Jackets");
            p.setQuantity((Integer) quantRainy.getValue());
             productList.add(p);
             populateData(productList);
        }
        if (checkWinterWear.isSelected()) {
            
            if(quantWinter.getValue().equals(check)){
                
                JOptionPane.showMessageDialog(null, "Please Add Quantity!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Products p = new Products();
            p.setProductName(String.valueOf(comboWinterProduct.getSelectedItem()));
            p.setProductType("FootWear");
            p.setQuantity((Integer) quantWinter.getValue());
            productList.add(p);
            populateData(productList);
        }
        
       
       
        ClothesRequirementRequest request = new ClothesRequirementRequest();
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent");
        request.setProductList(productList);
        
        

        for (Network n : business.getNetworkList()) {

            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {

                    e.setEnterpriseType(Enterprise.EnterpriseType.NGO);
                    if (e instanceof NGOEnterprise) {

                    for (Organization organization : e.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof NGOAdminOrganization) { //changed from shlter to ngo organization
                            organization.getWorkQueue().getWorkRequestList().add(request);
                            userAccount.getWorkQueue().getWorkRequestList().add(request);
                        }
                    }
                }
            }
        }
        
        JOptionPane.showMessageDialog(null, "Request Initiated Successfully!");
        
        //Clearing the selected options
        
       checkSummerWear.setSelected(false);
       checkWomenWear.setSelected(false);
       checkWinterWear.setSelected(false);
       checkFootWear.setSelected(false);
       checkRainyWear.setSelected(false);
       checkJackets.setSelected(false);
       
        comboSummerProduct.setEnabled(false);
        comboWomenProducts.setEnabled(false);
        comboWinterProduct.setEnabled(false);
        comboRainyProducts.setEnabled(false);
        comboJacketProducts.setEnabled(false);
        comboFootWearProducts.setEnabled(false);
        
        quantSummer.setEnabled(false);
        quantWomen.setEnabled(false);
        quantWinter.setEnabled(false);
        quantFootWear.setEnabled(false);
        quantRainy.setEnabled(false);
        quantJackets.setEnabled(false);
        
        btnReset.setEnabled(false);
        messageJTextField.setText("");
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

        public void populateData(ArrayList<Products> productList) {

        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();

        model.setRowCount(0);

            for (Products p : productList) {
                Object row[] = new Object[3];
                row[0] = p;
                row[1] = p.getProductName();
                row[2] = p.getQuantity();
                ((DefaultTableModel) tblProducts.getModel()).addRow(row);  
        }
    }
        
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

       checkSummerWear.setSelected(false);
       checkWomenWear.setSelected(false);
       checkWinterWear.setSelected(false);
       checkFootWear.setSelected(false);
       checkRainyWear.setSelected(false);
       checkJackets.setSelected(false);
       
        comboSummerProduct.setEnabled(false);
        comboWomenProducts.setEnabled(false);
        comboWinterProduct.setEnabled(false);
        comboRainyProducts.setEnabled(false);
        comboJacketProducts.setEnabled(false);
        comboFootWearProducts.setEnabled(false);
        
        quantSummer.setEnabled(false);
        quantWomen.setEnabled(false);
        quantWinter.setEnabled(false);
        quantFootWear.setEnabled(false);
        quantRainy.setEnabled(false);
        quantJackets.setEnabled(false);


    }//GEN-LAST:event_btnResetActionPerformed

    private void checkSummerWearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSummerWearActionPerformed
        comboSummerProduct.setEnabled(true);
        quantSummer.setEnabled(true);
        
        //*************** added recent ***********
    }//GEN-LAST:event_checkSummerWearActionPerformed

    private void checkWinterWearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkWinterWearActionPerformed
        comboWinterProduct.setEnabled(true);
        quantWinter.setEnabled(true);
    }//GEN-LAST:event_checkWinterWearActionPerformed

    private void checkRainyWearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRainyWearActionPerformed
        comboRainyProducts.setEnabled(true);
        quantRainy.setEnabled(true);
    }//GEN-LAST:event_checkRainyWearActionPerformed

    private void checkWomenWearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkWomenWearActionPerformed
        comboWomenProducts.setEnabled(true);
        quantWomen.setEnabled(true);
    }//GEN-LAST:event_checkWomenWearActionPerformed

    private void checkJacketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkJacketsActionPerformed
        comboJacketProducts.setEnabled(true);
        quantJackets.setEnabled(true);
    }//GEN-LAST:event_checkJacketsActionPerformed

    private void checkFootWearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFootWearActionPerformed
        comboFootWearProducts.setEnabled(true);
        quantFootWear.setEnabled(true);
    }//GEN-LAST:event_checkFootWearActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ShelterWorkAreaJPanel dwjp = (ShelterWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox checkFootWear;
    private javax.swing.JCheckBox checkJackets;
    private javax.swing.JCheckBox checkRainyWear;
    private javax.swing.JCheckBox checkSummerWear;
    private javax.swing.JCheckBox checkWinterWear;
    private javax.swing.JCheckBox checkWomenWear;
    private javax.swing.JComboBox<String> comboFootWearProducts;
    private javax.swing.JComboBox<String> comboJacketProducts;
    private javax.swing.JComboBox<String> comboRainyProducts;
    private javax.swing.JComboBox<String> comboSummerProduct;
    private javax.swing.JComboBox<String> comboWinterProduct;
    private javax.swing.JComboBox<String> comboWomenProducts;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JSpinner quantFootWear;
    private javax.swing.JSpinner quantJackets;
    private javax.swing.JSpinner quantRainy;
    private javax.swing.JSpinner quantSummer;
    private javax.swing.JSpinner quantWinter;
    private javax.swing.JSpinner quantWomen;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTable tblProducts;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
